In [2]:
import pandas as pd

# Profiler
---
This notebook analyzes the results of the models and aims to better understand the underlying structure of the data. The goal is to examine why the models assign a given user to a particular cluster and to interpret the characteristics that define each segment.


#### *PURCHASES_FREQUENCY*

The purchase frequency coefficient for **Cluster 3** is above **0.9**, and **Cluster 1** also shows a very high value, close to **0.9**.

In contrast, **Cluster 0** and **Cluster 2** exhibit significantly lower purchase frequency values, indicating that users in these groups make purchases much less often.

---

#### *PURCHASES_TRX*

The **number of purchase transactions** is another feature that clearly separates the clusters.

**Cluster 3** once again dominates in terms of transaction count, followed by **Cluster 1**.
The remaining two clusters (**Cluster 0** and **Cluster 2**) show the lowest number of transactions.

---

#### *PURCHASES_INSTALLMENTS_FREQUENCY*

A similar pattern appears in this feature.
**Cluster 3** and **Cluster 1** have the highest frequency of purchases made in installments, while **Cluster 0** and **Cluster 2** remain at considerably lower levels.

---

#### *Interpretation*

After examining several of the top features from the **feature importance ranking**, it becomes clear that **Cluster 3 stands out strongly from the others**. This suggests that the model can assign users to this cluster more easily.

The only misclassifications in the test data (exactly **three cases**) involve **Cluster 1**, which may be explained by the fact that the values of the examined features for these users were very close to those of other clusters.

In [3]:
data = pd.read_csv('../dataset/data_clusters.csv')
data

,CUST_ID,BALANCE,BALANCE_FREQUENCY,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,PURCHASES_FREQUENCY,ONEOFF_PURCHASES_FREQUENCY,PURCHASES_INSTALLMENTS_FREQUENCY,CASH_ADVANCE_FREQUENCY,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT,TENURE,cluster
0,C10001,40.900749,0.818182,95.40,0.00,95.40,0.000000,0.166667,0.000000,0.083333,0.000000,0,2,1000.0,201.802084,139.509787,0.000000,12,0
1,C10002,3202.467416,0.909091,0.00,0.00,0.00,6442.945483,0.000000,0.000000,0.000000,0.250000,4,0,7000.0,4103.032597,1072.340217,0.222222,12,2
2,C10003,2495.148862,1.000000,773.17,773.17,0.00,0.000000,1.000000,1.000000,0.000000,0.000000,0,12,7500.0,622.066742,627.284787,0.000000,12,1
3,C10005,817.714335,1.000000,16.00,16.00,0.00,0.000000,0.083333,0.083333,0.000000,0.000000,0,1,1200.0,678.334763,244.791237,0.000000,12,0
4,C10006,1809.828751,1.000000,1333.28,0.00,1333.28,0.000000,0.666667,0.000000,0.583333,0.000000,0,8,1800.0,1400.057770,2407.246035,0.000000,12,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8631,C19184,5.871712,0.500000,20.90,20.90,0.00,0.000000,0.166667,0.166667,0.000000,0.000000,0,1,500.0,58.644883,43.473717,0.000000,6,0
8632,C19186,28.493517,1.000000,291.12,0.00,291.12,0.000000,1.000000,0.000000,0.833333,0.000000,0,6,1000.0,325.594462,48.886365,0.500000,6,1
8633,C19188,23.398673,0.833333,144.40,0.00,144.40,0.000000,0.833333,0.000000,0.666667,0.000000,0,5,1000.0,81.270775,82.418369,0.250000,6,1
8634,C19189,13.457564,0.833333,0.00,0.00,0.00,36.558778,0.000000,0.000000,0.000000,0.166667,2,0,500.0,52.549959,55.755628,0.250000,6,0
8635,C19190,372.708075,0.666667,1093.25,1093.25,0.00,127.040008,0.666667,0.666667,0.000000,0.333333,2,23,1200.0,63.165404,88.288956,0.000000,6,0

### PURCHASES_FREQUENCY

In [5]:
data_purchases_frequency = data['PURCHASES_FREQUENCY']
data_purchases_frequency.describe()

count    8636.000000
mean        0.496000
std         0.401273
min         0.000000
25%         0.083333
50%         0.500000
75%         0.916667
max         1.000000
Name: PURCHASES_FREQUENCY, dtype: float64

In [11]:
data_x = data[data['PURCHASES_FREQUENCY'] > 0.92]
data_x['cluster'].value_counts()

cluster
1    1772
3     257
2      97
Name: count, dtype: int64

In [14]:
len(data[data['cluster'] == 3])

335

In [15]:
257 / 335

0.7671641791044777

In [16]:
len(data[data['cluster'] == 1])

3273

In [17]:
1772 / 3273

0.5413993278337916

In [18]:
len(data[data['cluster'] == 2])

1165

In [19]:
97 / 1165

0.08326180257510729

The filter shows that **8% of the users assigned to Cluster 2** have a **high purchase frequency above 0.92**. This percentage is not very small, but it is not particularly large either.

**CASH_ADVANCE** appears to be a feature that separates observations from **Cluster 2** quite well compared to the other clusters, which likely helps the model make accurate predictions. This is supported by the fact that we observe **only 7 misclassifications out of 229 observations**.

In contrast to **Cluster 2**, **Clusters 1 and 3** are more interesting in this context. More than **76% of the users in Cluster 3** have a **purchase frequency above 0.92**, and slightly above **54% of the users in Cluster 1** also have a frequency above **0.92**.

In [31]:
data_x = data[data['PURCHASES_FREQUENCY'] <= 1]
data_x['cluster'].value_counts().sum()

np.int64(8636)

### CASH ADVANCE

In [34]:
data_cash_advance = data['CASH_ADVANCE']
data_cash_advance

0          0.000000
1       6442.945483
2          0.000000
3          0.000000
4          0.000000
           ...
8631       0.000000
8632       0.000000
8633       0.000000
8634      36.558778
8635     127.040008
Name: CASH_ADVANCE, Length: 8636, dtype: float64

In [35]:
data_cash_advance.describe()

count     8636.000000
mean       994.175523
std       2121.458303
min          0.000000
25%          0.000000
50%          0.000000
75%       1132.385490
max      47137.211760
Name: CASH_ADVANCE, dtype: float64

In [37]:
data_ca = data[data['CASH_ADVANCE'] > 4000]
data_ca

,CUST_ID,BALANCE,BALANCE_FREQUENCY,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,PURCHASES_FREQUENCY,ONEOFF_PURCHASES_FREQUENCY,PURCHASES_INSTALLMENTS_FREQUENCY,CASH_ADVANCE_FREQUENCY,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT,TENURE,cluster
1,C10002,3202.467416,0.909091,0.00,0.00,0.00,6442.945483,0.000000,0.000000,0.000000,0.250000,4,0,7000.0,4103.032597,1072.340217,0.222222,12,2
22,C10024,3800.151377,0.818182,4248.35,3454.56,793.79,7974.415626,1.000000,0.083333,0.916667,0.333333,13,13,9000.0,9479.043842,1425.426525,0.000000,12,2
35,C10037,7427.076941,1.000000,0.00,0.00,0.00,8873.375046,0.000000,0.000000,0.000000,0.727273,11,0,9000.0,1636.361601,1986.843608,0.000000,11,2
38,C10040,1411.602230,0.454545,963.24,963.24,0.00,6173.682877,0.083333,0.083333,0.000000,0.333333,6,6,7500.0,20071.075440,719.948985,0.333333,12,2
47,C10052,4931.331857,1.000000,901.42,646.07,255.35,8530.648614,0.625000,0.375000,0.250000,0.875000,37,9,12000.0,8113.297346,1012.415961,0.000000,8,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8506,C19053,3335.053583,0.700000,0.00,0.00,0.00,5823.467109,0.000000,0.000000,0.000000,0.300000,3,0,7000.0,931.371718,1006.983314,0.000000,10,2
8531,C19080,3271.424058,0.888889,1173.28,0.00,1173.28,4122.912645,0.888889,0.000000,0.777778,0.333333,4,16,5000.0,817.177789,999.725550,0.000000,9,1
8548,C19098,2330.222764,1.000000,1320.00,0.00,1320.00,14926.790590,0.428571,0.000000,0.285714,0.571429,10,3,10000.0,8157.666434,283.362434,0.200000,7,2
8554,C19104,1382.936306,0.875000,336.00,0.00,336.00,4158.990631,0.875000,0.000000,0.750000,0.125000,5,7,4000.0,754.256439,681.059427,0.600000,8,1
8629,C19182,5967.475270,0.833333,214.55,0.00,214.55,8555.409326,0.833333,0.000000,0.666667,0.666667,13,5,9000.0,966.202912,861.949906,0.000000,6,2

In [41]:
data_ca['cluster'].value_counts()

cluster
2    536
0     27
3     16
1     11
Name: count, dtype: int64

In [42]:
536 / 590

0.9084745762711864

### Conclusion for the CASH_ADVANCE Feature

The general conclusion regarding the **CASH_ADVANCE** feature is that if a user exceeds **$4000 in cash advance**, it is highly likely that this user should be assigned to **Cluster 2**.

At this stage of the analysis, **more than 90% of the users who exceed this threshold belong to Cluster 2**, which indicates that this feature plays a strong role in distinguishing this cluster from the others.